name: Build and Deploy mdBook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install mdBook
      run: cargo install mdbook

    - name: Install Krita and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y krita xvfb

    - name: Convert Krita files to PNG
      run: |
        mkdir -p book/src/images
        for file in ArtWork/*.kra; do
          xvfb-run --auto-servernum krita --export --export-filename "book/src/images/$(basename "${file%.kra}.png")" "$file"
        done

    - name: Build mdBook
      run: mdbook build book

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
